# Generated by Django 4.0.1 on 2022-01-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
