# Generated by Django 4.0.1 on 2022-01-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_participants_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
