# Generated by Django 4.0.1 on 2022-01-28 23:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_participants_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='firstName',
            field=models.CharField(max_length=20, validators=[blog.models.validate_first_letter]),
        ),
        migrations.AlterField(
            model_name='participants',
            name='lastName',
            field=models.CharField(max_length=20, validators=[blog.models.validate_first_letter]),
        ),
    ]
